services:
  zurg:
    labels:
      - net.unraid.docker.webui:http://192.168.50.69:9696
      - net.unraid.docker.icon:https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/prowlarr-logo.png