services:
  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:latest    
    container_name: zurg
    restart: unless-stopped
    networks:
      - plexarr
    environment:
      TZ: America/Detroit
      PUID: 100
      PGID: 99
    ports:
      - 9999:9999
    volumes:
      - /mnt/user/appdata/debrid/core/zurg-testing/scripts/plex_update.sh:/app/plex_update.sh
      - /mnt/user/appdata/debrid/core/zurg-testing/config.yml:/app/config.yml
      - /mnt/user/appdata/debrid/core/zurg-testing/zurgdata:/app/data

  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    restart: unless-stopped
    networks:
      - plexarr
    environment:
      TZ: America/Detroit
      PUID: 100
      PGID: 99
    volumes:
      - /mnt/user/debrid/zurg:/data:rshared # CHANGE /mnt/zurg WITH YOUR PREFERRED MOUNT PATH
      - /mnt/user/appdata/debrid/core/zurg-testing/rclone.conf:/config/rclone/rclone.conf
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on:
      - zurg
    command: "mount zurg: /data --allow-other --allow-non-empty --dir-cache-time 10s --vfs-cache-mode full"
